/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <cstdint>
template<std::uint32_t address>
struct Register
{
	static volatile std::uint32_t& value()
	{
		// static functions call without creating an object;
		return *reinterpret_cast<volatile std::uint32_t*>(address);
		//function returns a reference to a 32-bit unsigned integer
		//reinterpret_cast<volatile std::uint32_t*>(0x40023830)
		//treat this number as the address of a pointer to a 32-bit volatile unsigned integer
		//(volatile std::uint32_t*)0x40023830
		//(volatile std::uint32_t*)0x40023830

	}
};

// storing all gpioa,gpiod,RCC adresss;
constexpr std::uint32_t RCC_AHB1ENR_ADDR=0x40023830;   //
constexpr std::uint32_t GPIOD_MODER_ADDR=0x40020C00;
constexpr std::uint32_t GPIOD_ODR_ADDR=0x40020C14;
constexpr std::uint32_t GPIOA_MODER_ADDR=0x40020000;
constexpr std::uint32_t GPIOA_IDR_ADDR=0x40020010;

class GPIO
{
public:
	static void enable_clock()noexcept
	{
		// struct name::func
		Register<RCC_AHB1ENR_ADDR>::value()|=(1<<3);
		Register<RCC_AHB1ENR_ADDR>::value()|=(1<<0);
	}
	static void enable_moder(std::uint32_t pin)noexcept
	{
		Register<GPIOD_MODER_ADDR>::value() &=~(3<<pin*2);
		Register<GPIOA_MODER_ADDR>::value()&=~(3<<0);
		Register<GPIOD_MODER_ADDR>::value()|=(1<<pin*2);
		Register<GPIOA_MODER_ADDR>::value()|=(0<<0);
	}
	static void toggle(std::uint32_t pin)noexcept
	{
		//GPIOD_ODR^=(1<<pin);

		if(Register<GPIOA_IDR_ADDR>::value()&1)
		{
			Register<GPIOD_ODR_ADDR>::value()|=(1<<pin);
			for(volatile std::uint32_t i = 0; i < 300000; i++);
		}
		else
		{
			Register<GPIOD_ODR_ADDR>::value()&=~(1<<pin);
			for(volatile std::uint32_t i = 0; i < 300000; i++);
		}
	}
};
void delay()
{
	for(volatile std::uint32_t i = 0; i < 300000; i++); //volatile- donit optimise the code
}
int main()
{
	constexpr std::uint32_t led_pin=12;   // create const named led_pin
	GPIO::enable_clock();
	GPIO::enable_moder(led_pin);

	while(1)
	{
		GPIO::toggle(led_pin);
		delay();
	}

}
