/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <cstdint>

constexpr std::uint32_t RCC_AHB1ENR_ADDR=0x40023830;
constexpr std::uint32_t GPIOD_MODER_ADDR=0x40020C00;
constexpr std::uint32_t GPIOD_ODR_ADDR=0x40020C14;
constexpr std::uint32_t GPIOA_MODER_ADDR=0x40020000;
constexpr std::uint32_t GPIOA_IDR_ADDR=0x40020010;

inline volatile std::uint32_t& RCC_AHB1ENR=*reinterpret_cast<volatile std::uint32_t*>(RCC_AHB1ENR_ADDR);
inline volatile std::uint32_t&GPIOD_MODER=*reinterpret_cast<volatile std::uint32_t*>(GPIOD_MODER_ADDR);
inline volatile std::uint32_t&GPIOD_ODR=*reinterpret_cast<volatile std::uint32_t*>(GPIOD_ODR_ADDR);
inline volatile std::uint32_t&GPIOA_MODER=*reinterpret_cast<volatile std::uint32_t*>(GPIOA_MODER_ADDR);
inline volatile std::uint32_t & GPIOA_IDR=*reinterpret_cast<volatile std::uint32_t*>(GPIOA_IDR_ADDR);

class GPIO
{
public:
	static void enable_clock()noexcept
	{
		RCC_AHB1ENR|=(1<<3)|(1<<0);
	}
	static void enable_moder(std::uint32_t pin)
	{
		GPIOD_MODER &=~(3<<pin*2);
		GPIOA_MODER&=~(3<<0);
		GPIOD_MODER|=(1<<pin*2);
		GPIOA_MODER|=(0<<0);
	}
	static void toggle(std::uint32_t pin)
	{
		//GPIOD_ODR^=(1<<pin);

		if(GPIOA_IDR&1)
		{
			GPIOD_ODR|=(1<<pin);
			for(volatile std::uint32_t i = 0; i < 300000; i++);
		}
		else
		{
			GPIOD_ODR&=~(1<<pin);
			for(volatile std::uint32_t i = 0; i < 300000; i++);
		}
	}
};
void delay()
{
	for(volatile std::uint32_t i = 0; i < 300000; i++);
}
int main()
{
	constexpr std::uint32_t led_pin=12;
	GPIO::enable_clock();
	GPIO::enable_moder(led_pin);

	while(1)
	{
		GPIO::toggle(led_pin);
		delay();
	}

}
